name: gravity
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - numpy
    - scipy
    - pandas
    - matplotlib
    - jupyter
    - jupyterlab
    - livereload
    - pyproj
    # Fatiando a Terra packages (used to check calculations and prepare data)
    - pooch
    - verde
    - harmonica
    - boule
